# Generated by Django 2.1.9 on 2021-06-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210608_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Transaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.transaction',),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Transaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.transaction',),
        ),
    ]
