# Generated by Django 2.1.9 on 2021-06-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_deposit_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='balance',
            name='book_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
